services:
  - type: web
    name: thetasummary
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: MONGO_DBNAME
        sync: false
      - key: WASABI_ACCESS_KEY_ID
        sync: false
      - key: WASABI_SECRET_ACCESS_KEY
        sync: false
      - key: WASABI_BUCKET_NAME
        sync: false
      - key: WASABI_ENDPOINT
        sync: false
      - key: WASABI_REGION
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: DEEPSEEK_URL
        sync: false
      - key: DEEPSEEK_MODEL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: SECRET_KEY
        generateValue: true 